In [1]:
import numpy as np

In [13]:
def sig(z):   #z is np array
    return 1/(1+ np.exp(-z))

In [3]:
def derivativeSig(sig_out):
    return sig_out*(1 - sig_out)

In [5]:
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array([[0,0,1,1]]).T

In [10]:
weights = 2 * np.random.random((3,1)) - 1     # random weights between -1 to 1
weights

array([[ 0.16417727],
       [ 0.42714051],
       [ 0.5367075 ]])

In [22]:
for iter in range(1000):
    Output0 = x
    Output1 = sig(np.dot(Output0, weights))
    # Output1

    first_term = Output1 - y
    second_term = derivativeSig(Output1)
    first_two = first_term * second_term    #common part for all weights
    third_term = Output0
    # changes = np.array([[0,0,0]])
    # for i in range(3):
    #     for j in range(4):
    #         changes[0][i] = changes[0][i] + first_two[j][0] * third_term[j][i]

    net_change = np.dot(Output0.T,first_two)
    learning_rate = 0.1
    weights = weights - learning_rate*net_change
    #print(weights)
Output1 = sig(np.dot(x,weights))
Output1,weights

(array([[ 0.52222107],
        [ 0.13223378],
        [ 0.52222107],
        [ 0.89239662]]), array([[ 3.90786663],
        [-1.88135089],
        [ 0.08894288]]))

In [28]:
weights0 = 2 * np.random.random((3,4)) - 1
weights1 = 2 * np.random.random((4,1)) - 1

In [32]:
for i in range(1000):
    
    layer1 = sig(np.dot(layer0,weights0))
    layer2 = sig(np.dot(layer1,weights1))

    l2_error = layer2 - y
    l2_delta = l2_error * derivativeSig(layer2)
    net_change2 = np.dot(layer1.T,l2_delta)

    l1_error = l2_delta.dot(weights1.T)   #error of each training data point distributes acc to weights 4*4
    l1_delta = l1_error * derivativeSig(layer1)
    net_change1 = np.dot(layer0.T,l1_delta)

    weights0 = weights0 - learning_rate*net_change1
    weights1 = weights1 - learning_rate*net_change2
layer0 = x
layer1 = sig(np.dot(layer0,weights0))
layer2 = sig(np.dot(layer1,weights1))
layer2

array([[ 0.53773425],
       [ 0.1656489 ],
       [ 0.53773425],
       [ 0.7847376 ]])